
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-16
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-role-student-bug","number":52,"title":"jl - bug fix, removed extra role_student from the codebase","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/52"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-FormatDates","number":51,"title":"WL - Feature: Format dates in Recommendation Requests Table","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/51"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"fix-changelog-master","number":50,"title":"jh - Fix changelog master .json file","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/50"},{"author":{"id":"U_kgDOB3CfIg","is_bot":false,"login":"suhritpadakanti","name":""},"headRefName":"sp-createpages","number":40,"title":"Sp createpages","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/40"}]
