
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-16
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-packagejson","number":49,"title":"WL - Revert changes to package-lock.json and package.json","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/49"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"WL-foreignkey","number":44,"title":"WL - Added foreign key relationship between RecommendationRequest and RequestType","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/44"},{"author":{"id":"U_kgDOB3CfIg","is_bot":false,"login":"suhritpadakanti","name":""},"headRefName":"sp-createpages","number":40,"title":"Sp createpages","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/40"},{"author":{"id":"U_kgDOB3CfIg","is_bot":false,"login":"suhritpadakanti","name":""},"headRefName":"sp-Requesttype","number":37,"title":"sp - Create RequestTypeForm for Admins and Professors with Storybook and Test","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/37"}]
