
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-16
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jl-user-role","number":28,"title":"Jl user role","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/28"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-pending-requests-page","number":27,"title":"dk - added recommendation request table to pending requests page","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-16/pull/27"}]
